### ISSUE TITLE
Using pipenv for deps managment

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/show-scraper#11]
Hey @kbondarev,

Would you be open to possibly using [pipenv](https://pipenv.pypa.io/en/latest/basics/) vs just regular pip + freezing deps?

Similar to [here](https://github.com/trailofbits/algo/issues/1868) where I made the case of using pipenv it's a lot easier way to manage your dependencies, and can add all your development dependencies in there as well (if you using pylint + black (or whatever linting + formatter you use)).

The other great thing you get out of using that is the inherit "freeze" via a .lock file, and it allows you to more easily upgrade things as well (via the [`pipenv update` command](https://pipenv.pypa.io/en/latest/basics/#example-pipenv-upgrade-workflow) (or via [this](https://github.com/elreydetoda/packer-kali_linux/pull/86#issue-743304189))).  It'll automatically handle setting up a virtual environment as well, or you can still have a local [venv](https://pipenv.pypa.io/en/latest/basics/#pipenv-and-docker-containers).

I've used it in GH actions [before](https://github.com/Climate-Refugee-Stories/crs-website/blob/c82f394a620b4631bb43de5ca4433d33a51bb292/.github/workflows/cd.yml#L25-L37) (thinkin about the JB website), so it works pretty well and even has a native [GH action caching](https://github.com/Climate-Refugee-Stories/crs-website/blob/c82f394a620b4631bb43de5ca4433d33a51bb292/.github/workflows/cd.yml#L31) as well.

I'd happily make a PR to implement these changes (to both this repo + the main JB repo), but I just wanted to see what you thought about it first before doing that work :sweat_smile:.

Good pipenv resources:
- [Video by author at pycon 2018](https://youtu.be/GBQAKldqgZs) (author or the requests package)
- [Really comprehensive guide to pipenv](https://realpython.com/pipenv-guide/)
- Using in GH actions ([ex1](https://github.com/Climate-Refugee-Stories/crs-website/blob/c82f394a620b4631bb43de5ca4433d33a51bb292/.github/workflows/cd.yml#L21-L37) & [ex2](https://github.com/Climate-Refugee-Stories/crs-website/blob/c82f394a620b4631bb43de5ca4433d33a51bb292/.github/workflows/cd.yml#L100-L122)) (one of my projects)
- [docs](https://pipenv.pypa.io/en/latest/basics/)

**Comment by kbondarev** [comment]
That's a good idea! Caching would reduce the time of the GH scraping action a little.

Personally, I'm a little bit more familiar with [poetry](https://python-poetry.org/). So naturally I'd prefer to use it instead of pipenv. But in the end I wouldn't mind pinenv either.
So... go ahead and setup either :)

**Comment by elreydetoda** [comment]
Yay :grin: , ya I've heard of poetry before and I've heard it's really good whenever you want to publish a package to pypi or any other python packaging place. (although I'm not super familiar with it to be honest)

Awesome, I'll get that taken care of then :grin: :rocket:

**Comment by elreydetoda** [comment]
closed by #19
