### ISSUE TITLE
Coder Radio 476 on JB.com URL error

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/show-scraper#22]
So, I was trying to work on the logic for the website's 110, and part of that I was trying to pull down more recent show information so I could get all the sponsors locally. Incidentally I used the latest_episodes environment variable and that was grabbing the most recent stuff from JB.com, and when it was my pydantic typing threw an error for Coder radio 476 saying that the URL wasn't right for the mp3 direct download link...

![image](https://user-images.githubusercontent.com/10230166/182840679-7c47679b-0e81-46b7-956b-6b80ae35c72f.png)

and sure enough it was right. I went to: https://www.jupiterbroadcasting.com/149367/tapping-the-breaks-coder-radio-476/ and the mp3 download link is missing an h in the https.

![image](https://user-images.githubusercontent.com/10230166/182840620-e4242b90-3872-43ab-9508-ea155a69958c.png)

Then i thought...how is mine failing on validation and the production version isn't, because JB.net has the right URL, and it looks like it might have happened after the episode was pulled down already because it was failing on the main one's GH action here: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/runs/7663513330?check_suite_focus=true#step:6:25

So, this'll require either @gerbrent or someone else from JB to fix it in wordpress.

**Comment by gerbrent** [comment]
I'm on it, nice investigative work! 🔍

**Comment by noblepayne** [comment]
Fixed. Thanks, @elreydetoda! :mechanical_arm:

**Comment by elreydetoda** [comment]
No problem, happy to help 😊
