### ISSUE TITLE
Episode direct download links - not working properly after deployment

### ISSUE THREAD

**Issue by elreydetoda** [JupiterBroadcasting/show-scraper#29]
When https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/pull/355 was merged during Office Hours 11, it removed the main jb.com site. This broke the functionality of the scraper to grab the direct download links.  This can be seen in this commit: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/e708639b2fac63754911954f556a59503c2e9fad

- [youtube](https://github.com/JupiterBroadcasting/show-scraper/blob/2f8bdaedb9e71d57301d0de40ad1644937d896be/scraper.py#L219):
  - There must be some way to get this information besides having to query the YT API for all JB shows, and then matching based on title name. Maybe some integration with Castablasta passing an environment variable for the YT id after publishing? (reference: https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/issues/215#issuecomment-1204742444)
- [video file:](https://github.com/JupiterBroadcasting/show-scraper/blob/2f8bdaedb9e71d57301d0de40ad1644937d896be/scraper.py#L216) I don't know how to generate the scale engine URL...I was hoping I could possibly template it out with whatever the URL is, but it looks like it's inconsistent across shows...
  - I think I can match all the way up to the last `/`: `http://201406.jb-dl.cdn.scaleengine.net/extras/2022/`
    - `201406` is probably just an account number for JB
    - `jb-dl.cdn.scaleengine.net/` is consistent for all shows
    - `extras` is the same as the fireside slug
    - `2022` is the current year
  - after that though there is some variance...
    - most shows do like this: `<slug>-<episode_number_with_zero_padding>.mp4` (i.e. [`extras-083.mp4`](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/e708639b2fac63754911954f556a59503c2e9fad#diff-154863ae4e13a14676b1e4fe64124babd3a2874eed3a90995732f95de626e3afL46))
      - but both the `<slug>` and episode number have variance.
      - on coder radio the "<slug>" portion is `cr` ([example](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/e708639b2fac63754911954f556a59503c2e9fad#diff-8a7758a03b231e647d64c43494704567faf0b2d627567e1426ecb2c645ebf53fL58))
      - some shows have a zero padding of 1 (i.e. [`cr-0476.mp4`](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/e708639b2fac63754911954f556a59503c2e9fad#diff-8a7758a03b231e647d64c43494704567faf0b2d627567e1426ecb2c645ebf53fL58)), but others have 2 (i.e. [`office-007.mp4`](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com/commit/e708639b2fac63754911954f556a59503c2e9fad#diff-c1e9c1b7c6036581eed36ac1ba7d5300bf8e031afc99f2f94eaf70b7d9aab8d5L214))
   - so, I think we'll have to have a castablasta integration here as well...
- [jb_url](https://github.com/JupiterBroadcasting/show-scraper/blob/2f8bdaedb9e71d57301d0de40ad1644937d896be/scraper.py#L220): this is no longer relavant, since the current page's URL is the JB URL.

**Comment by ChanceM** [comment]
Okay I figured this out and how to fix it. The issue is that the original site does not page at 1 but rather page one is index.html. I have a branch of the scraper that can use the copy @StefanS-O made to rebuild these files with the direct links intact. Should I just make a content commit to JupiterBroadcasting/jupiterbroadcasting.com with the fixed files?

Since this should only apply to the back catalog probably not worth editing the scraper...

**Comment by CGBassPlayer** [comment]
That awesome that you managed to figure out the direct download issue! Amazing work!

> Should I just make a content commit to JupiterBroadcasting/jupiterbroadcasting.com with the fixed files?

I would say yes as I believe I was told a while back that the scraper only looks at the 5 most recent episodes of each show. So the back catalog shouldn't be overwritten by the scraper automatically running.

> probably not worth editing the scraper...

I would have to agree as I don't think any new shows are coming anytime soon. But I would hold onto the code change just incase we need it in the future. Maybe in an extra branch on the repo or something.

**Comment by ChanceM** [comment]
Okay now with a bit better understanding of the issue I think I have found a possible, although not great method, for getting the YT links. It is dependent on JB maintaining the playlist of shows on YT. 

https://www.youtube.com/feeds/videos.xml?playlist_id=PLUW3LUwQvegxr9-RTGmzRcDs7bqsI1rSP

I have a branch of the script that will pull this feed and parse it for a match and populate the YouTube link to the episode. This feed only surfaces the last 5 episodes so it might work, so long as the shows are published in time for the scrape to pick them up.

**Comment by ChanceM** [comment]
Branch if anyone would like to check it out: [ChanceM/show-scraper/tree/feature/add-yt-direct-dl-link](https://github.com/ChanceM/show-scraper/tree/feature/add-yt-direct-dl-link)
